configs:
  params:
    server.insecure: true

global:
  domain: "argo.kars.tinnirello-livio.me"

redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1