sources:
  - gateway-httproute
provider: ovh
domainFilters:
  - tinnirello-livio.me
ovh:
  consumerKey: ""
  applicationKey: ""
  applicationSecret: ""
txtOwnerId: "acme.mycompany.example"
forceTxtOwnerId: true